version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
  test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Run tests
          command: python -m unittest app_test
    

workflows:
  ci-wf:
    jobs:
      - build
      - test
      # - test:
      #     requires:
      #       - build
